[package]
name = "fastcast"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
gpui = { package = "gpui-ce", version = "0.2.2" }
gpui_platform = { package = "gpui_ce_platform", version = "0.1.0", features = ["wayland", "x11"] }
linicon = "2.3.0"
resvg = "0.48"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tiny-skia = "0.12"
unicode-segmentation = "1.13.3"
